apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:1/uX9jLvfKmTcwpVBazekK7xPoTu2BSO8BM6FxrGFLU=,iv:8cgfER/3hDwtph7im3ufH7zVMAO+Dm4ZdLA+j4CcleI=,tag:2JhpdB8rRKnRPdBp/p83hQ==,type:str]
    admin-user: ENC[AES256_GCM,data:fRAFP7Y=,iv:d21X9ODyr2UbgfKueaLp5DP36Sq3Lm6onDnTWyj4yEE=,tag:gbnxTuxbDCo/ZGf38VBjIQ==,type:str]
    discord-webhook-url: ENC[AES256_GCM,data:gMQhMjXIkXdwP6i8tqJI75M6HN6mc+Jb7ojbjFL5gjiUAuWNqsZH8A06le+j1jlMIvyNyRqdHImP7V2SCbbNV6l9dZHs9MhUyR6wMAwu521EdqQjwVoUhv2THiq2wRbOSL6ZrjWtUmRRliHQt7AtEkC3H/CB4fvQpQJQqA==,iv:RrQ6M1Ec5/CbFWSQweNv4e006qbVKQQONcsVJIH9wGs=,tag:7rAs0U/kSwt4ZiqkV55AWA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bjhRVEhQSjNtWTFFUmti
            T1hmK1VaZUZRQjNjdTRuakJlTDM3UUNXTWhnCmtSQUxHQkh0NXRpQXNOL0QxYTZl
            SGNmVkVxSU9iRkxBeE5ISTdJcHlpWEkKLS0tIC9GOHlUTWxDN2pUUmlmQTJlYWhy
            NVpJRXU4Vjk5OU11MmZVZytlbFpxOTQKWMk9xpQjtNBX/ZKWwUZTN+YEEOVh6lFw
            fLT/qIumGwfx20ego9VtCxdqYknwycsmM3UANl/N44XcWjR6w/TO/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXUxeUhpbUdLcEg4SU9r
            Nm90U2lhNlFYMURITGlZQ2NBM1pJVFdiNGc4CjlpWlpwbWs5R0w4MHN6ZTc3VEJ4
            Nm4xK05RTE5MVjZjNE9acnhab0t0WlUKLS0tIHU4blRmbWp2QTE3OWlXdldpeVA3
            bEc3bUZMR1BlUi9OZkI0amNuZGdNYTgKx25loECPdiI8plqQ9Uhu4y+UAHjzr/fa
            haXPNPryBOot4Llvqd8oooNWR2Z8Cfm5C8da+yIi15TYINP7mv+P4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:05:11Z"
    mac: ENC[AES256_GCM,data:LuPAOixd3a/o5NNYtxNaMr1Xu4SbbZQXRUSCGrzyw5qmPJy0x5713srpjz746AnZuMAcy9uEeux74VT7/ckqnwhX/m0FBAfrnptAnIzndCYPeHElC0FEVGIxLUG4QKMnolU8P63IlKN4osAflnO611ZYq5RIwGyRifDlQDEAInQ=,iv:6DXegdXYpIdavMytdQawqnYctFJh7/MEZ1FVcqTSNCE=,tag:L5hNlgpgG1yYzqx0/h1Gtw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-dev-credentials
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:Q/f3ZMK8+oY=,iv:iBM1ZY4LRz6pHtWONV7sJeFN2+3pdx9kB1w0bHiJW7w=,tag:H4j8jfv/95g3xJFA4NDigA==,type:str]
    password: ENC[AES256_GCM,data:SsgPEs3t1gMbMljt29n58xdZv2JK0otBa9QMdfnFPNJ8G5R1YxGb5A==,iv:owCgNvmG96zGAE+E/SA0/p5YEFKkpHhqs/jJAfitwdk=,tag:rdWVGN7FHuGpEbAzpiRsaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bjhRVEhQSjNtWTFFUmti
            T1hmK1VaZUZRQjNjdTRuakJlTDM3UUNXTWhnCmtSQUxHQkh0NXRpQXNOL0QxYTZl
            SGNmVkVxSU9iRkxBeE5ISTdJcHlpWEkKLS0tIC9GOHlUTWxDN2pUUmlmQTJlYWhy
            NVpJRXU4Vjk5OU11MmZVZytlbFpxOTQKWMk9xpQjtNBX/ZKWwUZTN+YEEOVh6lFw
            fLT/qIumGwfx20ego9VtCxdqYknwycsmM3UANl/N44XcWjR6w/TO/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXUxeUhpbUdLcEg4SU9r
            Nm90U2lhNlFYMURITGlZQ2NBM1pJVFdiNGc4CjlpWlpwbWs5R0w4MHN6ZTc3VEJ4
            Nm4xK05RTE5MVjZjNE9acnhab0t0WlUKLS0tIHU4blRmbWp2QTE3OWlXdldpeVA3
            bEc3bUZMR1BlUi9OZkI0amNuZGdNYTgKx25loECPdiI8plqQ9Uhu4y+UAHjzr/fa
            haXPNPryBOot4Llvqd8oooNWR2Z8Cfm5C8da+yIi15TYINP7mv+P4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:05:11Z"
    mac: ENC[AES256_GCM,data:LuPAOixd3a/o5NNYtxNaMr1Xu4SbbZQXRUSCGrzyw5qmPJy0x5713srpjz746AnZuMAcy9uEeux74VT7/ckqnwhX/m0FBAfrnptAnIzndCYPeHElC0FEVGIxLUG4QKMnolU8P63IlKN4osAflnO611ZYq5RIwGyRifDlQDEAInQ=,iv:6DXegdXYpIdavMytdQawqnYctFJh7/MEZ1FVcqTSNCE=,tag:L5hNlgpgG1yYzqx0/h1Gtw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-staging-credentials
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:TNRg4hVlNo+zY/f+,iv:kbEc7u0P6FeexQwLOWenxrfnI3w3DzWq4uI3COirOI8=,tag:dUZz/Z2DrtKnCj2BAAmSxw==,type:str]
    password: ENC[AES256_GCM,data:sYmbEfrpHV3EipF/ny/SqR3Dib9EHfoBdFYJI04MKXMhkn7yBEq6yQ==,iv:+7hn4KCjlqrN8I9MLGKj43s4Axn5j3gpfgHJGG8rmZ0=,tag:uz3YbHJ6ZUVxepZ4xqGvag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bjhRVEhQSjNtWTFFUmti
            T1hmK1VaZUZRQjNjdTRuakJlTDM3UUNXTWhnCmtSQUxHQkh0NXRpQXNOL0QxYTZl
            SGNmVkVxSU9iRkxBeE5ISTdJcHlpWEkKLS0tIC9GOHlUTWxDN2pUUmlmQTJlYWhy
            NVpJRXU4Vjk5OU11MmZVZytlbFpxOTQKWMk9xpQjtNBX/ZKWwUZTN+YEEOVh6lFw
            fLT/qIumGwfx20ego9VtCxdqYknwycsmM3UANl/N44XcWjR6w/TO/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXUxeUhpbUdLcEg4SU9r
            Nm90U2lhNlFYMURITGlZQ2NBM1pJVFdiNGc4CjlpWlpwbWs5R0w4MHN6ZTc3VEJ4
            Nm4xK05RTE5MVjZjNE9acnhab0t0WlUKLS0tIHU4blRmbWp2QTE3OWlXdldpeVA3
            bEc3bUZMR1BlUi9OZkI0amNuZGdNYTgKx25loECPdiI8plqQ9Uhu4y+UAHjzr/fa
            haXPNPryBOot4Llvqd8oooNWR2Z8Cfm5C8da+yIi15TYINP7mv+P4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:05:11Z"
    mac: ENC[AES256_GCM,data:LuPAOixd3a/o5NNYtxNaMr1Xu4SbbZQXRUSCGrzyw5qmPJy0x5713srpjz746AnZuMAcy9uEeux74VT7/ckqnwhX/m0FBAfrnptAnIzndCYPeHElC0FEVGIxLUG4QKMnolU8P63IlKN4osAflnO611ZYq5RIwGyRifDlQDEAInQ=,iv:6DXegdXYpIdavMytdQawqnYctFJh7/MEZ1FVcqTSNCE=,tag:L5hNlgpgG1yYzqx0/h1Gtw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-kirro-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
stringData:
    email: ENC[AES256_GCM,data:NbnRhailn94ZHerErzg3viO2XUtrL+dm,iv:EI3sMhuT3FxnYYBRh3QXdF5ujUCjS99zfarkFcUr0c8=,tag:QyPjJGlady1c6Xdea5gWvw==,type:str]
    password: ENC[AES256_GCM,data:FttzgtCvBo88Ugo3Dy1W2LeVJA2NWpkngSla/vd5Hfs=,iv:FhsZKmUBz5oLVacyrsbixhkK95SvsNk2yXYOTQNfuSQ=,tag:JP2hJ4mIlHlj94B4+JYUfg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bjhRVEhQSjNtWTFFUmti
            T1hmK1VaZUZRQjNjdTRuakJlTDM3UUNXTWhnCmtSQUxHQkh0NXRpQXNOL0QxYTZl
            SGNmVkVxSU9iRkxBeE5ISTdJcHlpWEkKLS0tIC9GOHlUTWxDN2pUUmlmQTJlYWhy
            NVpJRXU4Vjk5OU11MmZVZytlbFpxOTQKWMk9xpQjtNBX/ZKWwUZTN+YEEOVh6lFw
            fLT/qIumGwfx20ego9VtCxdqYknwycsmM3UANl/N44XcWjR6w/TO/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXUxeUhpbUdLcEg4SU9r
            Nm90U2lhNlFYMURITGlZQ2NBM1pJVFdiNGc4CjlpWlpwbWs5R0w4MHN6ZTc3VEJ4
            Nm4xK05RTE5MVjZjNE9acnhab0t0WlUKLS0tIHU4blRmbWp2QTE3OWlXdldpeVA3
            bEc3bUZMR1BlUi9OZkI0amNuZGdNYTgKx25loECPdiI8plqQ9Uhu4y+UAHjzr/fa
            haXPNPryBOot4Llvqd8oooNWR2Z8Cfm5C8da+yIi15TYINP7mv+P4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:05:11Z"
    mac: ENC[AES256_GCM,data:LuPAOixd3a/o5NNYtxNaMr1Xu4SbbZQXRUSCGrzyw5qmPJy0x5713srpjz746AnZuMAcy9uEeux74VT7/ckqnwhX/m0FBAfrnptAnIzndCYPeHElC0FEVGIxLUG4QKMnolU8P63IlKN4osAflnO611ZYq5RIwGyRifDlQDEAInQ=,iv:6DXegdXYpIdavMytdQawqnYctFJh7/MEZ1FVcqTSNCE=,tag:L5hNlgpgG1yYzqx0/h1Gtw==,type:str]
    version: 3.13.3
