apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-it-s3-config
    namespace: seaweedfs-it
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:muHKBFuexaNV+lL993kfSiy9KMBJmJ0vwYzDDr+L17QGsd9kwXam8OoAxMrz2ybMTnxdJ0hbGbEKdiYsIuc4Ub+Zre0zKg+P7DKVcDmlm4rmm8BgEMWJOXI9x7q3RW2eHB5phN0N40SYCACzTJ1A7ej3r3InyLS1A8qkpekRyi7D4Mv5Bh4H24bPGoaNKpT1PrVq1JvatsLFAdNvVY3bbonI+t/QHRxcbflSbDvJnLH8oBOsE2F71hcho3X2mcfui+NDJbV+HEXKjb6bgN0/oQkceq+Hhf5GH3QC4qxhswFSv0/7SV06D9bvfooM8LPWh4gRw0vNUr5U8O68Q8yB8Z1u7VoTpHhUXSz9EtSGLgYoPIt53wPnWcsBNeFnCUcIOsE6hlDagLkr0B+yZKS54oJ0XA2/UYtpAZdJcY/YjP0Uo39sKXg7MLftrH+DyVIt14m5geh7XFE6WprqMKHuXOoLRigQJNy+L11qog==,iv:l9YQP0Eqy4Drq6wsXMoT2d2rmGzd2BzDOR0Rrq2lda0=,tag:cX/TA7Npqk0oEK6i0MbdkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VWRvbnlvaG9TZGJPZWh5
            dXpRZ2paRGN6MkcreFpibGRVNmR4VitPR0h3CnVyZERLOXNWZmtmckR2TVdFMEs4
            WGFOanRMTXVSa2ZkNGh2TURtbUdwL1UKLS0tIGoxVXF1STJETHdMNWVZR3U3cVpZ
            bHRkbEpqb3dZS1RTdE90M1BkSS81cHMKtLCBzcq88gxbNGtC902qe6KpDgaTKeXt
            14P/Lcfd1uP7kLiCpdaWBlR06VudIM1EEeHfdskQpREbbcZVwZqoSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ3dqVE5aWWFVN1NqZlVO
            UjBnbk85c1VwQXhZdW1oWlM0blU5VUtUTERvCmhxRE9STVZDOWhLeENVSzFQU3hR
            TityYXdJbjQ5VUc5RWhJYkdmY0owc0kKLS0tIEt2U25Cd2xab0RYZ0s2ckNBdkJi
            Z2Q2Vy9ZQzNaWTdlWE1ZSks1azBBbTQKAKQiqcfh1e2Xy4LcKVggwJp6L36Eq0oI
            EMq2QI6HaKUGpt3Mpy45nSdcqzDiuojtxjuALqBAYPUwa/Wvy7wFvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T12:49:44Z"
    mac: ENC[AES256_GCM,data:uviwmNddLutoF2Z2gl8KZASBn0S7cDb+9Ge1mMf7pdl0MCB36Wrgs1Mhz0bYMBSJshJUR0+fqTMQqU0teP00HgQ4P2dd0ajgKlOBLDl0EJLsCMLtycV23t9PWeH4Yg+Pll5zluuzc8N4mPeiFerjZmfFaO5D8dQpm7k7HR/4epQ=,iv:UrqhmqYgLuTr55ayRHa96XFqkBfLwiWwnwyYirmQuOI=,tag:kUDw9NN7Ez7V1bJnJRitEQ==,type:str]
    version: 3.13.3
