apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: prism-streaming-rag-env
stringData:
    GROQ_API_KEY: ENC[AES256_GCM,data:/tsaNlzV+W+EJs0L5lvB+YcLEfkT9Gqd3+XUjVT+ZAkTYvR93rT9fMSOmWfw6aJFL0atumGVwrQ=,iv:bgRNUvF/HysDVAnQipQEt8bzjPD9avlIzWYeY/zCK5I=,tag:n5qQVE8MSdPpuPVEkpsyGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RVFjbGJpSE91S0l3Z3Bh
            ZTRWeXhVOGFPdzRTblNHSlFvbG5kTWhGc2o0CkR0WjFKODZLRnE3TGJVK09UbTdX
            MHNTbUplRUdnWjVtWDlHa0RVVUJMaHMKLS0tIEpmUWk2UFpWOUtwNktsTncvZmtj
            NVhMYWRlTlN4QUZWcEJrNC9oQWVTM0kKqnjPh5oVq0sWZxwEYPee8W46OkKXCdOM
            rsbRYp+JShgK9x7IQCXry0T0HYCAGxg7o7f/AXBRLcbiD8WEKZysew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMFNRcVFoZC83dHdBYVJP
            TUJKaGRDNE5tQk5td3Y4eGR4TUxab1RTM1RNCk5qWm9WbUhERll4eElqcEdpUmcz
            K2FqR3haVFRCVWhjakxKcU5EVlpFSU0KLS0tIDFIUWl2UjdGeDFJeWRRaUtrWW43
            RUN0S0dnODc2VkY2RDJHVWxLaHlNOHMKQSxQo7Hd5VwpefmGSev/q+saXX+wFoDM
            cb+tm0NmXMyTZAmiOGk2Ac36oD5IvGVbkCIrS9F8iPgFHC2bytivQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T15:08:49Z"
    mac: ENC[AES256_GCM,data:J7vFuFfp+crPPiMK3oxU+TJKaAlZXSs0xL8BnddiWdWdUXxM1O1UaGqm7XxDQ8TVP4J+p+F3iJ+264rLp2u9UG637lpEAvLA+TgGJUM60dTEflZN7nkhs2rVr+30uux3ygNn995QC2HBa0Hd5TfsJQ+Ploz+CPKQkgZUJi4I+OQ=,iv:1EUIsEiPXlnC3sZIFTAWRDa1uHBYrJu7Bv1I0n2KHPk=,tag:/tbiFvQ3wuYlLXUX6AHsBw==,type:str]
    version: 3.13.3
