apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: prism-streaming-rag-env
stringData:
    GROQ_API_KEY: ENC[AES256_GCM,data:R1t571VCamEX2zvChdhlwyIiwfe3rg5WiEJBR6j0qsKT5WfXczS0Ye5KS7C8j/DpP0s1jX/RlHk=,iv:1PiBlV4x53sQ8fbBGvuBJe4N2LhTuVsPWjozlbHFs3w=,tag:YLanQAhYBwjzGreqLArZ2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RGxyQmRsT211VnRmMnpY
            a0MxRlpOaTMrcnhPc1llcXJHRlZxWnJzYW5VCkFkSXRVMW80SkdycXJTWDhtc3Fy
            azVxcWJQeHprRTFzZE11bDdZUGdobWcKLS0tIEd3RUE2dCtsZU0yb01aTWkrTkE1
            dzZxTG5XV1N1dlU0dzlyNmUvK21FYmMKmiKMWuYUvSDWziaqf8L1kmOfRG6YM9pX
            01xbCSgxPoKIZnh0VS9NSPqH6GYU+uB5fFm9p2K8g+sROM931Tf/iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYWxQM2YzdTc5Z2E3RjVn
            S2dMK0RCbjNUS3ZHcnlSVG5OTFhORkZldVdNCnFIODlmM0MwMVpFVFp2UmlPVnFk
            ZWFJVjByRmNzZms3R2xrdHpuMnFpV28KLS0tIGhqV29lYmdXbnVqRFIvTTk0Uk5l
            N2ZTUDVhZG0xVnVxaVNYbElDbzNuVGsK55SyGxiwB61IC8Mz4DJs026IjS6qgcyC
            etUWt571OrHVg4VAyqQNKVkNe/uezGUFpxQfuMZsvvIb4ae5EJ6Kbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T15:12:01Z"
    mac: ENC[AES256_GCM,data:KDVMxh16qTMuZb7zEIhwtqXJAwKJdLEaBYvfPLDH9rp9D7dVCV/7STB6m3TIpTIT2RrMpjnrhGbVoDxrBpPVI9DQzXe0NHYf2DFeCtcf0+u7SPWLqGpnR0RCaX9sLt0Y5eo3Xel/X8ZM8ALIgUwPMyc6gYDUxizsxS73703xyG0=,iv:Q5ij5stz3nzYHSpapo/NvP6aBhadIhx4hmhQS86Jfsc=,tag:fnbhxDJIJKHlikNaIOVAaQ==,type:str]
    version: 3.13.3
