kustomize:
  images:
  - ghcr.io/upayanmazumder/devjourney/html-nodejs/web=ghcr.io/upayanmazumder/devjourney/html-nodejs/web:latest@sha256:5f09513c9e17bae357590a7c478d068b13d3a38944fe9bb9ec0f98e9db2c8af2
