apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repo-creds
    name: repo-creds-devlabs
    namespace: argocd
stringData:
    type: ENC[AES256_GCM,data:2b76,iv:zZgAAY7ShhDEWp7gXDTEnRxa7Li0CDpxEyCG1f2lLRI=,tag:B8Mpk2BhQByBAD+gKYKB5Q==,type:str]
    url: ENC[AES256_GCM,data:BJA9oOeOhd/q5xySLG1zjQZVf1AbqCHoOR3Xpf+06sHjRv3P1tkirQ4=,iv:7yeUQtA+lNjkK/jVdJrT8nOSp8Fl0KjrzfPvOHmcSuE=,tag:0g+Hvy7qCuP6hkdZVIJUDA==,type:str]
    username: ENC[AES256_GCM,data:DvqdD31NklizuHBqEZ4=,iv:BuvWM+qgVOV5RUFiCQn+JIu5s4MLyMxIbTmB5uZkyFs=,tag:6g4uN8mJWGby2zHItbw1LQ==,type:str]
    password: ENC[AES256_GCM,data:u5vgpFP03+MoeMN2GZHLPt0PftcOkikgeX8Zf0dvqFmhcJcEr955dg==,iv:gjzKW01tjn02gh1CG5dB74fdG6YNgEvrEM0QBh6Wczc=,tag:yqgMpSwK1+RhrMK6JScUQQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnRPN0dEWEIvUEFWaW1F
            b3ZyeDlPblZyd0tRK3RDakx6OUxoWkQ2RUYwCk9qRnRsaUJuVkQ1ZS82cERzTjBn
            VnZpL2liS1l6Uk1Pd0JlaUJhMVRqa00KLS0tIHhRcTEvUkdMclJYbjlFanFKaER1
            T2VsSHJyUGRQdzlCRlRIVi9HZG5keGMK/ne3wBJDNIddMkAhJajGc8XaCBI23mc3
            zhPco+MKvMjZ4kKdoodkI34vUVeWtswGfwahFsnopFT4e+0SDzOsOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeld4ZGFJWndpekxsbVFR
            RVJLU2pqVlNhYTdlYXo3VjdJRHhETDVrU2hNCmdaczY2UVRCeHdiazYwV2hxTzdq
            WVV6cDZlVlBmOFphUmxLK1E0VS82QUUKLS0tIE5NdWlWdzRJMFdCN3F2M012RCtm
            Q1RpUVpTekROVlpFbGlRQ2VHTjE4RmcKwf60SQJp4HmEZFi1O4NTsLFoinq8+T/5
            ZJJAVhfT/BnQtvU+TeBgSNj16kYCoPvE5eG+EFv5bWjQbtzlI73Jbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:57:22Z"
    mac: ENC[AES256_GCM,data:lXVACEdny0OR8xlEqERZGWwUA3zQ1kFEU4j7am522zAwJ8X8PsumOQ/CM+xP4LuZNhAluh1AHXGdYQU07KMHVQnOkGNsLVcW8Cx4q77KYvJ9Tu3gETMHC8d1WjBaAHGEwFSHT6wljHT0IL8CAfOO5/gGOjuHIvIEtRVEwMFcaII=,iv:ZNj/jliWuAZHe+9sRPN0NJRFrywZhQKuc0x498hzSpQ=,tag:Fv0PRSKXqWS+3f3c0K19+A==,type:str]
    version: 3.13.3
