apiVersion: v1
data:
    admin.password: ENC[AES256_GCM,data:88subwOw/PLO/ciiA0CE8Qe+jezHH7Lkruh6FQGVs/3pcklktplOauA9p/ZLmnDZinbuHdZVgSEkT3v0npa/9eN1vpxCNNIFk7sve5Ha548=,iv:bGAxb59S2r8bxi8xsQGU6c+U1vGTV7SbzIv6y5zA8Qs=,tag:QfTuxu02KjRmXaePWzGF+A==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:WFrMlTOdMbw3HOKyODNGInGINBebrA7oBCDv6g==,iv:aKm8yfOlwcAyEC0dBLnGDtZUkr1u/ubvT9M67LSqdQM=,tag:T/5W7uHbnkD/XG6iKm6C9A==,type:str]
    server.secretkey: ENC[AES256_GCM,data:NQlBQeSaSTum0Ijq1AFPw1LT8mVFgiLHXZCSue5yJm18JAiQcGqGmvgHZfQH32Gi9ci1dJotM8Tmi3FX,iv:RP7WD+4JuAH7ycrpGQibiqH3v/9a/T3UMbT1fXk8Fag=,tag:DNf18dK2scXgDDfzYQkvdg==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: argocd-secret
    namespace: argocd
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xOdW82bW5FUWlHV0lE
            ZVZLa2RVSDY2Qlh1cjN5RnJzY3U4NjI2cVJBCm1kMytIaEoxOFJHbCtsajdMTUdt
            clF0VUdyUnlEWDRySTFia0VRMlBRTWsKLS0tIElWdnc1YVI3R1BhaTBpMzdtdzRR
            NytPZmQzMmVCU3pLdWRlM01vRlVaY1UKQ68giukfC7pDw/S68dAcm0TU6x1KUEbd
            JKl99iXUXQlR0QkyATH8CZX/TEjeDpgtY2Tg8ku4LQW/bRRXh9G16A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmg5WnZpRStVNm1rT2Jh
            N25RcS9WTEFtQmFmWENFc1lhcnFSb2Vad1JvCmhPSlNyVkF5QmZaTVBoYmZHNXVX
            akppZVYvMVExM3NEZWxPVFFwa3pZcVEKLS0tIHlVMWFQQ2pFRXc3OVA1K3ZQZUV2
            d1BOMk83UHhKMW56Q3kzdDlHc3lpOUkKdPcW3Fu/RfXckCUTWi0Ei9GOZNLxl5Be
            DL+ShafABLOWRrHiuLiympwaiG4+8Cqq6lO9xFch8aFE9bLLQS6cSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:42Z"
    mac: ENC[AES256_GCM,data:XPTAqgXAdGZvatjABanIGXYCpraIigJcrG/Mdvr5REpNoyoQyrrQMq0ZoLaC+Lu9zk9mQNKZCqszbYOVOZ4ABt8Kzg1Zn8WIbtz5UrHJ/9UTmxqBeIXDeMbsEeZ2S0Nrew+ZPOe8x+9YbsnS4IzEjtn3KHqZdbxXKHb5fzKTiEY=,iv:OtN/7tLd9nWLuGerqqs9dY7joQcR6TFseUyLRxRxrzM=,tag:olj+86W34m7B2dHMQXvuiA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: git-creds
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:bGpa5FhbQ0DKwhI3oTDmL0gy4dIN+5hKkwwTooIKPvX6ijm0zcvepw==,iv:NXVb1aryccGmFkvJj7AMwLulLUtc6UDPsn2b2aWs/dM=,tag:yg2rRxL8TZvOIC6yZQ7JYg==,type:str]
    username: ENC[AES256_GCM,data:KNQbv6nJjzGdHpxrS2s=,iv:9H6DIYEjVcC2+bVXOEk1LpIGn+a8Ea/efmPnVayCOqg=,tag:X2/CsXxDNVaxJpveKY6m3g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xOdW82bW5FUWlHV0lE
            ZVZLa2RVSDY2Qlh1cjN5RnJzY3U4NjI2cVJBCm1kMytIaEoxOFJHbCtsajdMTUdt
            clF0VUdyUnlEWDRySTFia0VRMlBRTWsKLS0tIElWdnc1YVI3R1BhaTBpMzdtdzRR
            NytPZmQzMmVCU3pLdWRlM01vRlVaY1UKQ68giukfC7pDw/S68dAcm0TU6x1KUEbd
            JKl99iXUXQlR0QkyATH8CZX/TEjeDpgtY2Tg8ku4LQW/bRRXh9G16A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmg5WnZpRStVNm1rT2Jh
            N25RcS9WTEFtQmFmWENFc1lhcnFSb2Vad1JvCmhPSlNyVkF5QmZaTVBoYmZHNXVX
            akppZVYvMVExM3NEZWxPVFFwa3pZcVEKLS0tIHlVMWFQQ2pFRXc3OVA1K3ZQZUV2
            d1BOMk83UHhKMW56Q3kzdDlHc3lpOUkKdPcW3Fu/RfXckCUTWi0Ei9GOZNLxl5Be
            DL+ShafABLOWRrHiuLiympwaiG4+8Cqq6lO9xFch8aFE9bLLQS6cSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:42Z"
    mac: ENC[AES256_GCM,data:XPTAqgXAdGZvatjABanIGXYCpraIigJcrG/Mdvr5REpNoyoQyrrQMq0ZoLaC+Lu9zk9mQNKZCqszbYOVOZ4ABt8Kzg1Zn8WIbtz5UrHJ/9UTmxqBeIXDeMbsEeZ2S0Nrew+ZPOe8x+9YbsnS4IzEjtn3KHqZdbxXKHb5fzKTiEY=,iv:OtN/7tLd9nWLuGerqqs9dY7joQcR6TFseUyLRxRxrzM=,tag:olj+86W34m7B2dHMQXvuiA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: repo-vcap-backend
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:pSB/kAn+RXu19tHSb4O2DJnu7Pzujna1v8v5sa0JtnTFJntFvjs1dA==,iv:hZ6Qsd7JLaDIiFgGdeLcwFijDaI5uxG9de0cs2hFGEw=,tag:+3DW+F6ddeC9OhoPk6B/4A==,type:str]
    type: ENC[AES256_GCM,data:jcCR,iv:qIk95i9EqcXxocxJTZLUpM8JMuqjwvXgqLeAALuLo1s=,tag:Qa3GGLg9NH+eC7A+3U9V2w==,type:str]
    url: ENC[AES256_GCM,data:PCB5hsmyAwNjxFu9V38FqTPsvB7AakMTtip3V/2XVJVoCrCO9Vm+vlvTXr0bnJrU/90SfOL0AejKx8la,iv:YY0/MWI6YDQ8Xnx8j5b4fMwC9kfxIgsaTFRSCmJB01Y=,tag:m6HVUNBKRcHsyJLycDVU5g==,type:str]
    username: ENC[AES256_GCM,data:/YOE7HnIihadCBwLGzg=,iv:mnhw6vYbpBJLV1jccEutLkcBz9OxmkKCZnOVMgADQOU=,tag:EYDQbf/36UrFcB8/siFwPA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xOdW82bW5FUWlHV0lE
            ZVZLa2RVSDY2Qlh1cjN5RnJzY3U4NjI2cVJBCm1kMytIaEoxOFJHbCtsajdMTUdt
            clF0VUdyUnlEWDRySTFia0VRMlBRTWsKLS0tIElWdnc1YVI3R1BhaTBpMzdtdzRR
            NytPZmQzMmVCU3pLdWRlM01vRlVaY1UKQ68giukfC7pDw/S68dAcm0TU6x1KUEbd
            JKl99iXUXQlR0QkyATH8CZX/TEjeDpgtY2Tg8ku4LQW/bRRXh9G16A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmg5WnZpRStVNm1rT2Jh
            N25RcS9WTEFtQmFmWENFc1lhcnFSb2Vad1JvCmhPSlNyVkF5QmZaTVBoYmZHNXVX
            akppZVYvMVExM3NEZWxPVFFwa3pZcVEKLS0tIHlVMWFQQ2pFRXc3OVA1K3ZQZUV2
            d1BOMk83UHhKMW56Q3kzdDlHc3lpOUkKdPcW3Fu/RfXckCUTWi0Ei9GOZNLxl5Be
            DL+ShafABLOWRrHiuLiympwaiG4+8Cqq6lO9xFch8aFE9bLLQS6cSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:42Z"
    mac: ENC[AES256_GCM,data:XPTAqgXAdGZvatjABanIGXYCpraIigJcrG/Mdvr5REpNoyoQyrrQMq0ZoLaC+Lu9zk9mQNKZCqszbYOVOZ4ABt8Kzg1Zn8WIbtz5UrHJ/9UTmxqBeIXDeMbsEeZ2S0Nrew+ZPOe8x+9YbsnS4IzEjtn3KHqZdbxXKHb5fzKTiEY=,iv:OtN/7tLd9nWLuGerqqs9dY7joQcR6TFseUyLRxRxrzM=,tag:olj+86W34m7B2dHMQXvuiA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: repo-vcap-frontend
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:G8b6odmGd0nreoRQRI2VK9lyk/vgHg3sTGH2BsQDOIc1yhmSP1A2Pg==,iv:gMwObwJKqw+76IDMvxzW7B5o+7VZd9OKz0ldVVhEff8=,tag:Z+VajbqiiqAPJCkpKnrIoQ==,type:str]
    type: ENC[AES256_GCM,data:I5xx,iv:d/itokeZsDyaKEDkKm8OghgSpnU6EAN95RZ6aiQfwno=,tag:AdLc26KiBIVstVRtQxJQtA==,type:str]
    url: ENC[AES256_GCM,data:BbrQiiT4ZJXrpOEt0U7H58N2INGHrOL4PpxKGxjhwBZXktLF+GAs6d+Jrb5nJWUqiTsGmFHq9udHBXXH7Q==,iv:7Cz2M6E9TzcEfSMqCZho8wdPrZhtKVV6kYLHnI4jkJ4=,tag:yS2ReOMZBxhZTSHvxRpbtg==,type:str]
    username: ENC[AES256_GCM,data:Kccc33MwT8OFhWPPYzM=,iv:n2isoSE91RXaNkWa/fw3u3g4dgku4IHfNB+nGncJmcA=,tag:OdUHjIe5EqdhdcNYaH89ww==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xOdW82bW5FUWlHV0lE
            ZVZLa2RVSDY2Qlh1cjN5RnJzY3U4NjI2cVJBCm1kMytIaEoxOFJHbCtsajdMTUdt
            clF0VUdyUnlEWDRySTFia0VRMlBRTWsKLS0tIElWdnc1YVI3R1BhaTBpMzdtdzRR
            NytPZmQzMmVCU3pLdWRlM01vRlVaY1UKQ68giukfC7pDw/S68dAcm0TU6x1KUEbd
            JKl99iXUXQlR0QkyATH8CZX/TEjeDpgtY2Tg8ku4LQW/bRRXh9G16A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmg5WnZpRStVNm1rT2Jh
            N25RcS9WTEFtQmFmWENFc1lhcnFSb2Vad1JvCmhPSlNyVkF5QmZaTVBoYmZHNXVX
            akppZVYvMVExM3NEZWxPVFFwa3pZcVEKLS0tIHlVMWFQQ2pFRXc3OVA1K3ZQZUV2
            d1BOMk83UHhKMW56Q3kzdDlHc3lpOUkKdPcW3Fu/RfXckCUTWi0Ei9GOZNLxl5Be
            DL+ShafABLOWRrHiuLiympwaiG4+8Cqq6lO9xFch8aFE9bLLQS6cSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:42Z"
    mac: ENC[AES256_GCM,data:XPTAqgXAdGZvatjABanIGXYCpraIigJcrG/Mdvr5REpNoyoQyrrQMq0ZoLaC+Lu9zk9mQNKZCqszbYOVOZ4ABt8Kzg1Zn8WIbtz5UrHJ/9UTmxqBeIXDeMbsEeZ2S0Nrew+ZPOe8x+9YbsnS4IzEjtn3KHqZdbxXKHb5fzKTiEY=,iv:OtN/7tLd9nWLuGerqqs9dY7joQcR6TFseUyLRxRxrzM=,tag:olj+86W34m7B2dHMQXvuiA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: creds-github-upayanmazumder
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repo-creds
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:98Cc,iv:AQrsOpzL+bR9TdJ89qliBGRdjUPhmy/TOQ11WNVYnNU=,tag:l9XUjOoGrv8VqIJxCxvYcg==,type:str]
    url: ENC[AES256_GCM,data:u/04ICSEUl8wle77ppLqs4vDpkkc9l5p+wkuTw3HfS3J6A==,iv:3BuQFSdkEliSSLTZWW43JfKd6PMalVqj0pR/OPevJ/0=,tag:6JOvgioNOSdb8j0Maq7rew==,type:str]
    username: ENC[AES256_GCM,data:Y/nNN3LyKfN6R7q9PLY=,iv:v1Ll5VcwGGTDZcBy0/qovMeo7VBXRD1TPqnYb8wZuO0=,tag:hddR/N7MlKjY+jHnjqKANQ==,type:str]
    password: ENC[AES256_GCM,data:xaBRCDa1KaS13a7YloI86XxEUQ0Wzb9VnqLzNzCSIrw5BNzCGVVkpw==,iv:WJBOxzSoIPrx4k1HbWT4gxXxb97c6bdbWcmAZvXcNtY=,tag:DHmTB0jjfIdkEQXYk/ydzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xOdW82bW5FUWlHV0lE
            ZVZLa2RVSDY2Qlh1cjN5RnJzY3U4NjI2cVJBCm1kMytIaEoxOFJHbCtsajdMTUdt
            clF0VUdyUnlEWDRySTFia0VRMlBRTWsKLS0tIElWdnc1YVI3R1BhaTBpMzdtdzRR
            NytPZmQzMmVCU3pLdWRlM01vRlVaY1UKQ68giukfC7pDw/S68dAcm0TU6x1KUEbd
            JKl99iXUXQlR0QkyATH8CZX/TEjeDpgtY2Tg8ku4LQW/bRRXh9G16A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmg5WnZpRStVNm1rT2Jh
            N25RcS9WTEFtQmFmWENFc1lhcnFSb2Vad1JvCmhPSlNyVkF5QmZaTVBoYmZHNXVX
            akppZVYvMVExM3NEZWxPVFFwa3pZcVEKLS0tIHlVMWFQQ2pFRXc3OVA1K3ZQZUV2
            d1BOMk83UHhKMW56Q3kzdDlHc3lpOUkKdPcW3Fu/RfXckCUTWi0Ei9GOZNLxl5Be
            DL+ShafABLOWRrHiuLiympwaiG4+8Cqq6lO9xFch8aFE9bLLQS6cSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:42Z"
    mac: ENC[AES256_GCM,data:XPTAqgXAdGZvatjABanIGXYCpraIigJcrG/Mdvr5REpNoyoQyrrQMq0ZoLaC+Lu9zk9mQNKZCqszbYOVOZ4ABt8Kzg1Zn8WIbtz5UrHJ/9UTmxqBeIXDeMbsEeZ2S0Nrew+ZPOe8x+9YbsnS4IzEjtn3KHqZdbxXKHb5fzKTiEY=,iv:OtN/7tLd9nWLuGerqqs9dY7joQcR6TFseUyLRxRxrzM=,tag:olj+86W34m7B2dHMQXvuiA==,type:str]
    version: 3.13.3
