#
# Noodle's write-back credential for the RANKSTACK repo.
#
# A write deploy key on upayanmazumder/rankstack, titled `noodle`:
#   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKTb3BDunI/VxRziFvXfCbg+pzSNotEHvsmPLyGQyweD noodle@upayan.dev
#
# `insecure: "false"` keeps strict host-key verification on.
apiVersion: v1
kind: Secret
metadata:
    name: git-creds-rankstack
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
type: Opaque
stringData:
    sshPrivateKey: ENC[AES256_GCM,data:0gQ94DwKS2CNCHQsO0cKlFeqtGHWzxeY6IbQ69ouKXm4bKJJcQyc0S1OGqoNRNba7zWIfjZJkjezOlzTJdDRTjezzx14RxE0JkyQIl6VT1w/+l9x7K/kqhWCFGpLABgmB5OvrCzu0XATyA7oCUr3Tk30nIfeSRmwST1kJEGtbfLOXYfleQwT1e2o8ysjSNPt2A3/gYe0ClJmSsQwW85gn8YcPlAsRXgvvsHjyEM/NPQNHfIa/2+gBbkkR0oAmjL2Q5i/sw38oqXoiHVuRhIjzrjTSORdeb+1q13w0Wur+TY5BpCiQF5cGkaqCGulLuMra8loDenjW8XUsGHkwQOz8FBNLmg0q4+vieopkwXlrj7fJC6xaKNJ+4bF6+vtB5AObf+BoOWFt7SYyn2znnlPqCf3nJWuVFYCVlkGV9uuu4/z+QPaQGVM9U5tnPXF71lDQnBwVkgHcoH0BHTkfk16qVLrGfXa8Ti3AOv9ACDfg4SYeOb7pJiftY0jTgn/H5y7UXRJX5eIxaDLYaORXxi612E6Js1J/J1Q7/BW,iv:0tJCxPZC/uOEGlADhA7HWuniQrjpo14Oh6uKQO3y9vM=,tag:lUzKueqMXOiH9fkhs84VSg==,type:str]
    insecure: ENC[AES256_GCM,data:hzY5JJM=,iv:ui2XzI2amG1dKIFri1Etar3CUWiT+65ap/J2KejBzQ0=,tag:DDHHnoeWSYxp5X+1SWH8Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVkFyWmdOV1JFaWZaaE83
            V09nUThxV3pmbmhHRHFKQmZSVG4yd0lBU0IwCkUyQkNjQVVlcTI3Z2F1UEowWFBO
            V1FJMVFpd3hka0M0WnRucmNXc0JFNG8KLS0tIE1RRDh3MXFrVUM2NkxiSTBnK1Q2
            WDcrcDEwL2R1dWpGb2poY1pTUzhwcWsKLAl1uGelKfqCxgBOPp/K9BtlxF1mdcqs
            5+3iGhrNXGaSeSRA+ex/ipMja9OWgGNad8C/gqGbR6BF8ppfKq/tdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY28veGM4bHhNaDEzaUNy
            WmVaL05kL0xYTXEwTUFlYkJIVGdXT0J6OUdjCmRaRDFWblYxcFhvSzdleEpLeXpx
            eXkySHlHU2dCR0hTRGtWZG94SUQwbm8KLS0tIE41SFFTNEN5T1BRN21sMmJYclc0
            bmY3UVEwNHNEaVU0Y0cvNTFFWkpYWDAKEODxMeJlXB/lHCnt3Te0LigL57PmHiIO
            5pcXtjldI6lFlFrA+f3LryyU//wBVcw5qR3ceridX8cHwFilxWbIzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T22:21:43Z"
    mac: ENC[AES256_GCM,data:O8zA4z0S9w89HgpNblGhqqn1Z9ayhcoUOggwCqOZ1QbYx5thessK/l104uNfW49fgBc4CAXU5pKL/IWPeoeZy5ytEC8yT5DZcJSt8fys6FecieKUMCnKXMHITyg67QKdJo31R7ApQomS+XErFzOSj8A/FtA+G8Qub92OTBG7Czk=,iv:gH2tofzdxt/2G+ktvfKvMc6cwikrgN4Xv7wMp4Zf/uw=,tag:GeNzPtgEjr/wd38ge6M0vw==,type:str]
    version: 3.13.3
