kustomize:
  images:
  - ghcr.io/upayanmazumder/devjourney/learning-react=ghcr.io/upayanmazumder/devjourney/learning-react:latest@sha256:81f4a0a95a9b559b7b342e911ef2750a69bc630658c3f6026ebb5925e6f7cb32
