kustomize:
  images:
  - ghcr.io/upayanmazumder/devjourney/learning-react=ghcr.io/upayanmazumder/devjourney/learning-react:latest@sha256:f29d466d8b6465d474c171a28c9b229304aa839ffa9a25461f21500481684bfb
