kustomize:
  images:
  - ghcr.io/upayanmazumder/devjourney/learning-react=ghcr.io/upayanmazumder/devjourney/learning-react:latest@sha256:68415e6cbce579b79c0396790e48b406f123d42d2662b8d8fe85926342bc1798
