apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: backend-env
    namespace: vcap-v1
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:BLjJ/eXrLHM9LmLQeUxjVlHb9WQVd22BWZLQI7ZxOxTpJHVcdA9su2Dra8HYYpTIHa++gjLErhGgxLnbbt1X3zyyCMjfUDfYRYzAn/l1Bi7BvnNi8SRWCid/L1P0xmZ9ad5IVvOfKiJvTwz0Grk3TfLWzA==,iv:ge9t13k/T71E3glK7mSJBDVFiN9qFVqKwqkZ2CwH3C4=,tag:4LOuPKXdS76wcufK4j36dw==,type:str]
    DATABASE_URL_SYNC: ENC[AES256_GCM,data:/9bHPQK5oz2A+r1tNbhzZAouL9aIRrMC6jZNtN+GVe3M+W+ChB86KDe6snMSwja8xifNxuOaN6z+uT3mRB7pTnu2ERRJ0r9jKy64hQdGGK73Toz2z6AfndyC3v1lgLi3/Hd/Y/wmVHvA5tkugojdl3YrZQ==,iv:IPVdc8hkEKb2XDBIcYBBdc8OSrVsLM9qxd4Md13By30=,tag:uEDcrsvy7ZNPK9J6Jhu/pg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:fACNl09qQCSEgaj4UdfqPqyT4drJtvnM2NtEIgIOdw8ORT5M,iv:egjcw4iJNIb0bIe4ZKCK0t+jqqGbzuj/tniDo9OUDrs=,tag:KrCcUp8kdudVrKPdG+7z6w==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:afUap6B69Yt7XDPpczenaH+fczMz7Ww07wZnkL4mD9ir/GJ6y7gQJGPaA7ybjsNg7S8b39plR93MaDnL5C6Cag==,iv:5TMONyLdi2wgNNF0cIx5KGpdI5ACoAyGmMW1uS66WI0=,tag:QK3ZwppDfB94yiDF4WIV7Q==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:vQJM0z0/shsAKU019RdKhrnV,iv:O/eN9eAPYWTm6uvygT+NrZDtgsYrG2L2zg5OuSRp4M4=,tag:a6CbZj65b23+3a/dUdYq7Q==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:zPNzUQaCBuhgaJ1giXvqG5MVXQ==,iv:EolWMsaGcCwhsuwP/qk4V2ZLO1j83gWN0Ui5IqEXfs4=,tag:rc/toRX7YoUx4HJqlU9kDg==,type:str]
    SIGNING_CERT_PASSWORD: ""
    POSTGRES_DB: ENC[AES256_GCM,data:oFfERaXrV0CpU75x6ek=,iv:NzJmh12euAKyCmLZpsOlZ0lF7gNZPfVR6HESSWvh2bE=,tag:peS0c4breBh/UZ2oP93oCg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:KkI13hMj2HM=,iv:QSnV279Zw3PXBzQId6LaYqks9Hl/orqshdRc4zLv9zY=,tag:G5rrl58GcPmeuqQsWhUI8g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QluTaFdrFpPPLBW/qef56QmNnoFNTmvF8ZfYio/B42Uh2eOKfEgvnA==,iv:07vdKAjIqdz5f6o4ttBT/4XWt4ew+mcKgXQCEMWTXGc=,tag:kVdUcXAfkVpfGAI3SiKWEA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUZVRzBVY251aWwwaHI2
            ZzZrbldTWnhRUjNUL1hjdDdvbE5maCtmU0VjClhCSUdwN2xiZ3lqYWxSUlBsNm1G
            Uk9hWHMzV0ZjWVptZDFEQ1BJNTR3K1UKLS0tIGw2R2pxTnBsUUJsTFZDNkwrRU9M
            WEVDbmpvRC9jN1JGRWNIbkFPcVN0ZDQKd0wf+WbW08eKDA4Y8ZmTXl1f880OWJC/
            BXYWIArtwLbBn3a8DMdOIW7r89Hp9FnjOJnAGX3n8X/qLsx6PrlYbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbnBOZFBkVmlBWU9PZEtL
            cFdZdDVwWXdlTkxFcmxsOTgxWWlqUHJNM1JnCjZiV1l6aUVPaHZwR3l6cUR3Y3J0
            WWZvdlVXRTdhQmpPV2Z4dEFTMzlYMVEKLS0tIGZZUkkyT1B5elBzVUNGcDY3RnI2
            dE9EM0pYUE11SnYzL0thTUhvbW9xNTQKcyFWWZ4sF8B8uXKZZCVEcoKv5xWKhehJ
            LKNodLn5g2V6m1nl+b/3Rj5xVIBo4Z5TfJc3TIPuOQAnD0C/RmmHvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:40:56Z"
    mac: ENC[AES256_GCM,data:MSUwDInw1d+rD8U43raJENzRPmHOYiQGCVY+s72IFzEMidPwWRy8LQT9DmD5xFfgCTl/ul8oS+xqoCNUFhcFChko3mSrVXhhqHUzk2l3B1WJhlaiXbIqhNeyRhg8T2DZa1wVS3+/+XB7UJ+hKQZIJxmhWinLxy9bhSNVq0vogbE=,iv:cI7KoHLa9f4wwTTaGl+8hncw+/z1THziRdGBGPdFwNc=,tag:k67SByJJnxvUuOw28ilzlg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: auth-env
    namespace: vcap-v1
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:0tQPabQQUIbU2X8xYV96HbdO30hxLsHJ6V/XZP6un2Mf2tjDT1oVS6SPbKcut6vmIqOxpdZmvj0vNg6O/iHTdPl6Z2rsH/tIUQwkEYBIpQWq/Uj00zARGfygZmwcdFMsyL3v3EKbK9pfirg=,iv:ChkhQsOKaJ2yJR9d5W5tnd8bI5TRss+85sfa/3aA+LU=,tag:QZHvSIhQKgavkxos1FgpKg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:g1SO2jBEiPRRuf/kaOTHyXmGWD3wz0VkbRWJd+chn9StMNn2,iv:9nUNN1BDecdgjH0zIph7Z8l0JEqvUOMJjE4nYoMWsRA=,tag:dtyDuh8nkFrHSeGLtV1OEg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:ocmf1k+zpX67R74p1DvEHdeDbMawn9F4GJl8aAfXRQHQG6crolzpLkKA+PC6q6SxJ0BrUSfLiC/2getmfGfV5VmB8XyeV8c=,iv:Ea9YR6VRHo0qFXpJ/0DZGDHPsgT89U2SqYMezIe6Ncg=,tag:+xL7cYxalu57Wdsdtag1/Q==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:81b7PuV986SEwveM1p/MIfTGWOcnEy5+ku5uJhTIAHvgc5E=,iv:hlFW4WydTxe9hfyaJHNZu/fpRz9UE94XMJZG4X9fFRM=,tag:q22T8oL9nQ+I+4GWwXqlBA==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:VMP/Baa81V4829AzIelZI9T6SUjKzVR5ZPYeHqCp9CZauZfC4obYRz/GpNEm4/UePKtqbF7CyiKWuF2mRBJ4XQ==,iv:vaUgO8buz66bg/Tl4lyELTWHXHlePOKXvLfw8AhEtHQ=,tag:hlkIZ9xBMEFw+BwVC/hEAA==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:ncpTYxZNwjNSS6L/0+Kw7LEtnOmYHInXtCchkRbCdOe3uskSHKUfCYnek9drEDt4bNvVdktJaljmczbOoo2p8A==,iv:JHnGk9x1c8h56xLY82zQ5DG1WXIFR3/41gQ3ZNAQ/qo=,tag:o2M7dUo3fuhGApTbXFeCnA==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:+ZgwAYtqalaQM+q9lAvrdJtLCLcuUJUr5ZcQ5eGnwc/ozN4VrAblmUp/DfZcDwLUHCx2dhdtYMNE8/cOoS0xRQ==,iv:37BV9QI+B0cTz2knktLUDWtcNhr3zVwjf1u/WgQNSws=,tag:BVizYrhsicGYMgYqX8MpIg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:wcytA38q+W6BSKCANtlbJ6JT,iv:68Yvs88MsN4gzC8QS5Jabol0zgsvqdNStdPX/6ObXPg=,tag:oi8B+0v1G3/Wbvb8G8FLjA==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:hXVKb++lmoMZTMHbvdizlU7xWA==,iv:j8lrgdPQ0UvPXA539PIYflbqQtIix2zTRNGN66YWe0g=,tag:bQ0iPbGnPTibIG5QaArO7w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUZVRzBVY251aWwwaHI2
            ZzZrbldTWnhRUjNUL1hjdDdvbE5maCtmU0VjClhCSUdwN2xiZ3lqYWxSUlBsNm1G
            Uk9hWHMzV0ZjWVptZDFEQ1BJNTR3K1UKLS0tIGw2R2pxTnBsUUJsTFZDNkwrRU9M
            WEVDbmpvRC9jN1JGRWNIbkFPcVN0ZDQKd0wf+WbW08eKDA4Y8ZmTXl1f880OWJC/
            BXYWIArtwLbBn3a8DMdOIW7r89Hp9FnjOJnAGX3n8X/qLsx6PrlYbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbnBOZFBkVmlBWU9PZEtL
            cFdZdDVwWXdlTkxFcmxsOTgxWWlqUHJNM1JnCjZiV1l6aUVPaHZwR3l6cUR3Y3J0
            WWZvdlVXRTdhQmpPV2Z4dEFTMzlYMVEKLS0tIGZZUkkyT1B5elBzVUNGcDY3RnI2
            dE9EM0pYUE11SnYzL0thTUhvbW9xNTQKcyFWWZ4sF8B8uXKZZCVEcoKv5xWKhehJ
            LKNodLn5g2V6m1nl+b/3Rj5xVIBo4Z5TfJc3TIPuOQAnD0C/RmmHvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:40:56Z"
    mac: ENC[AES256_GCM,data:MSUwDInw1d+rD8U43raJENzRPmHOYiQGCVY+s72IFzEMidPwWRy8LQT9DmD5xFfgCTl/ul8oS+xqoCNUFhcFChko3mSrVXhhqHUzk2l3B1WJhlaiXbIqhNeyRhg8T2DZa1wVS3+/+XB7UJ+hKQZIJxmhWinLxy9bhSNVq0vogbE=,iv:cI7KoHLa9f4wwTTaGl+8hncw+/z1THziRdGBGPdFwNc=,tag:k67SByJJnxvUuOw28ilzlg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: pull-secret
    namespace: vcap-v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:dSXGy2CsM9DwOZsyS32d7TvMG41vG8NrOxp8rFAs9LBLZDMA1bjJhOjcRkLitTNiLUmYfVW1iYlDivRZtb+dKe/wo5tacdDyW8M2NN9aSQvrLszTvngkWAcfQyJhO7FukqxhT4WpEblQX1M+rzSi0Q==,iv:nVZO6BLnF96g5JoIW0dMxJZ5BAknNA6NiYMzvQ8Lyw8=,tag:TqMnfoFqdMrSS6ARr2hy7w==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUZVRzBVY251aWwwaHI2
            ZzZrbldTWnhRUjNUL1hjdDdvbE5maCtmU0VjClhCSUdwN2xiZ3lqYWxSUlBsNm1G
            Uk9hWHMzV0ZjWVptZDFEQ1BJNTR3K1UKLS0tIGw2R2pxTnBsUUJsTFZDNkwrRU9M
            WEVDbmpvRC9jN1JGRWNIbkFPcVN0ZDQKd0wf+WbW08eKDA4Y8ZmTXl1f880OWJC/
            BXYWIArtwLbBn3a8DMdOIW7r89Hp9FnjOJnAGX3n8X/qLsx6PrlYbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbnBOZFBkVmlBWU9PZEtL
            cFdZdDVwWXdlTkxFcmxsOTgxWWlqUHJNM1JnCjZiV1l6aUVPaHZwR3l6cUR3Y3J0
            WWZvdlVXRTdhQmpPV2Z4dEFTMzlYMVEKLS0tIGZZUkkyT1B5elBzVUNGcDY3RnI2
            dE9EM0pYUE11SnYzL0thTUhvbW9xNTQKcyFWWZ4sF8B8uXKZZCVEcoKv5xWKhehJ
            LKNodLn5g2V6m1nl+b/3Rj5xVIBo4Z5TfJc3TIPuOQAnD0C/RmmHvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:40:56Z"
    mac: ENC[AES256_GCM,data:MSUwDInw1d+rD8U43raJENzRPmHOYiQGCVY+s72IFzEMidPwWRy8LQT9DmD5xFfgCTl/ul8oS+xqoCNUFhcFChko3mSrVXhhqHUzk2l3B1WJhlaiXbIqhNeyRhg8T2DZa1wVS3+/+XB7UJ+hKQZIJxmhWinLxy9bhSNVq0vogbE=,iv:cI7KoHLa9f4wwTTaGl+8hncw+/z1THziRdGBGPdFwNc=,tag:k67SByJJnxvUuOw28ilzlg==,type:str]
    version: 3.13.3
